### ISSUE TITLE
ARG argument on Dockerfile seems to be not needed

### ISSUE THREAD

**Issue by JordiGarcL** [docker/getting-started#1]
I believe`mkdocs` does not make special use of this environment variable.

https://github.com/docker/getting-started/blob/5bb26cc53af820cd1fb61142b2faf47f7582391f/Dockerfile#L30

**Comment by mikesir87** [comment]
Ah! Good catch. This is an artifact from where this repo came from ([dockersamples/101-tutorial](https://github.com/dockersamples/101-tutorial)), which was being translated into multiple languages. We decided to skip that (for now anyways), but that ARG snuck through.
