### ISSUE TITLE
Persisting Our Data section

### ISSUE THREAD

**Issue by steveknoblock** [docker/getting-started#10]
It's not clear where a terminal window needs to be opened to see the data.txt file. When I opened a terminal in VS Code at the project level, it couldn't find the data file to cat. I went to the Docker dashboard clicked on open terminal, did and ls, and there was the data file with the random number. It would be helpful if this part were clearer.

**Comment by mikesir87** [comment]
Sorry to hear about the confusion! Do you have any specific recommendations on how we can make it clearer there? You're also welcome to make a PR with the change (we can help provide pointers on how to do so if you need them).

**Comment by StefanScherer** [comment]
Thanks @steveknoblock for the suggestion. I've created a PR #35 to use the Dashboard to exec into the ubuntu container.
