### ISSUE TITLE
Max pull request reached at first use

### ISSUE THREAD

**Issue by Grizzly44115** [docker/getting-started#101]
Hello all,
the first action to check if docker is well installed is the docker run hello-world.
But it answers 'You have reached your pull rate limit.'

I'm running as root user on centos 7. My VM is behind a proxy. I've defined the proxy values for http and https in a manually created /etc/systemd/system/docker.service.d directory.

Here is the result of test described here: https://www.docker.com/blog/checking-your-current-docker-pull-rate-limits-and-status/
# curl --head -H "Authorization: Bearer $TOKEN" https://registry-1.docker.io/v2/ratelimitpreview/test/manifests/latest 2>&1
HTTP/1.1 200 Connection established

HTTP/1.1 200 OK
Content-Length: 2782
Content-Type: application/vnd.docker.distribution.manifest.v1+prettyjws
Docker-Content-Digest: sha256:767a3815c34823b355bed31760d5fa3daca0aec2ce15b217c9cd83229e0e2020
Docker-Distribution-Api-Version: registry/2.0
Etag: "sha256:767a3815c34823b355bed31760d5fa3daca0aec2ce15b217c9cd83229e0e2020"
Date: Fri, 20 Nov 2020 09:34:31 GMT
Strict-Transport-Security: max-age=31536000
RateLimit-Limit: 100;w=21600
RateLimit-Remaining: 0;w=21600

**Comment by mcardinalupgrade** [comment]
I am having the same issue here with the following steps to reproduce:

```
# Make no docker requests for days

# Try to fetch node:14.5.0
$ docker pull node:14.5.0
Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

# Check current limits
$ export TOKEN=$(curl "https://auth.docker.io/token?service=registry.docker.io&scope=repository:ratelimitpreview/test:pull" | jq -r .token)

$ curl --head -H "Authorization: Bearer $TOKEN" https://registry-1.docker.io/v2/ratelimitpreview/test/manifests/latest
HTTP/1.1 200 OK
Content-Length: 2782
Content-Type: application/vnd.docker.distribution.manifest.v1+prettyjws
Docker-Content-Digest: sha256:767a3815c34823b355bed31760d5fa3daca0aec2ce15b217c9cd83229e0e2020
Docker-Distribution-Api-Version: registry/2.0
Etag: "sha256:767a3815c34823b355bed31760d5fa3daca0aec2ce15b217c9cd83229e0e2020"
Date: Mon, 28 Dec 2020 04:37:32 GMT
Strict-Transport-Security: max-age=31536000
RateLimit-Limit: 100;w=21600
RateLimit-Remaining: 0;w=21600
```

Why is this happening?

**Comment by mikesir87** [comment]
Hello all! Rate limits can apply for a variety of reasons and are quite often seen when you're in an environment where a single egress IP address is used for many machines (such as a corporate environment). When this occurs, you can login to a Docker Hub account and your rate limit will be tied to you instead of the IP address. [More details can be found in the docs here](https://docs.docker.com/docker-hub/download-rate-limit/).
