### ISSUE TITLE
Wrong long syntax reference url

### ISSUE THREAD

**Issue by FantasqueX** [docker/getting-started#106]
The long syntax reference in docs/tutorial/using-docker-compose/index.md is wrong.
For example, It is https://docs.docker.com/compose/compose-file/#long-syntax-3
and it should be
https://github.com/compose-spec/compose-spec/blob/master/spec.md#long-syntax-3.

**Comment by StefanScherer** [comment]
Thank you for reporting this. I've merged a PR to fix the links.
