### ISSUE TITLE
page highlighting not working.

### ISSUE THREAD

**Issue by quroom** [docker/getting-started#108]
![image](https://user-images.githubusercontent.com/39736691/103067408-2d5cd380-45fe-11eb-9d1f-b1684b01e695.png)

The highlighting syntax doesn't show exactly.
When build page, there might be problem.
I tested it in my local with docker-compoe from this code.
The page works well.

![image](https://user-images.githubusercontent.com/39736691/103067532-79a81380-45fe-11eb-8b5b-53cff255681b.png)

Please check [this page ](https://docs.docker.com/get-started/08_using_compose/)

**Comment by mikesir87** [comment]
Thanks for letting us know and apologies for the long delay in getting back to you. This issue has been resolved, so all should be good to go now!

If you have any further questions or feedback, feel free to open a new issue (and we'll do better at responding in a more timely manner)!
