### ISSUE TITLE
Clarify where to put the files such as Dockfile

### ISSUE THREAD

**Issue by tristar500** [docker/getting-started#117]
Please tell the reader that the "Dockfile" goes inside the "app" folder.

**Comment by mikesir87** [comment]
Thanks for opening this issue and sharing your struggles. We apologize it's taken so long to respond to you.

The tutorial has been updated and hopefully resolves this issue. It now states the Dockerfile should be located in the same folder as the file `package.json`. 

If you have any further ideas to make the guide easier, please don't hesitate to open a new issue!
