### ISSUE TITLE
Ambiguous Host Network (2 matches found based on name)

### ISSUE THREAD

**Issue by amulyamalla** [docker/getting-started#123]
Os: Centos 7
Container Orchestrator:  Kubernetes 
-------------------------------------------

When server got rebooted , container could not come up with existing host network where as multiple host network automatically created with same name resulting a bulk failure  of application 
Manual intervention by deleting the network and restart the docker engine will resolve the issue , But i have below point that will help us to understand and  RCA 

Wants to know : 
 1. Why this occur ?
 2. Reson behind this ?
 3. How to restrict ? 
 4. Any impact after resolution ?

**Comment by mikesir87** [comment]
Thanks for taking the time to open an issue and apologies for the long delay. Unfortunately, it sounds like the problem you're experiencing is beyond the scope of the getting started guide, so we're going to close the issue.

If you're still having trouble, feel free to comment and let us know. Thanks!
