### ISSUE TITLE
"Error /app/node_modules/sqlite3: Command failed" when starting dev-mode container

### ISSUE THREAD

**Issue by mariohuq** [docker/getting-started#129]
I follow tutorial from Use bind mounts / [Start a dev-mode container](https://docs.docker.com/get-started/06_bind_mounts/#start-a-dev-mode-container).

After I run

```
docker run -dp 3000:3000 \
     -w /app -v "$(pwd):/app" \
     node:12-alpine \
     sh -c "yarn install && yarn run dev"
```

and run `sudo docker logs -f <container-id>`, I got

```
yarn install v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error /app/node_modules/sqlite3: Command failed.
Exit code: 126
Command: node-pre-gyp install --fallback-to-build
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Arguments: 
Directory: /app/node_modules/sqlite3
Output:
/bin/sh: node-pre-gyp: Permission denied
```

Container don't creates then. What means Exit code 126? How to solve it?

**Comment by mikesir87** [comment]
Hi @mariohuq 👋  Apologies for the delay in responding to your ticket.

We have made several updates to the project since this date, which should have resolved this issue. If you're still experiencing problems, feel free to create a new ticket and we'll be happy to investigate. Thanks!
