### ISSUE TITLE
Dockerfile location not specified in "/tutorial/our-application/2

### ISSUE THREAD

**Issue by benjcrouch** [docker/getting-started#13]
It wasn't clear to me that the Dockerfile had to be inside the App folder. I put it in the parent folder which I'd extracted the zipfile into.

The file built, and ran, but stopped with something like "File not found: /app/src/index.js"

**Comment by mikesir87** [comment]
Ah! Sorry for the confusion about that. Would you like to make a PR to help clarify that issue or do you want us to make a stab at it? We're always happy to have other contributors help out, so if you'd like to help but need some pointers, just let us know.

**Comment by benjcrouch** [comment]
sorry for the delay in replying. I'd like to help, and take but I'm just starting with GitHub too, and will probably end up causing more work for everyone if you leave me to write the PR (Pull Request?).

Thanks for your support.

**Comment by kosalanuwan** [comment]
@mikesir87 Can you specify where to put the Dockerfile? Is it inside the /app folder or outside /app folder? I am getting the same error as @benjcrouch mentioned. Still getting used to Docker but happy to send a PR if I get some pointers to try out `getting-started` app up and running.

**Comment by epflyingzhang** [comment]
I had the same confusion while following the tutorial.

**Comment by mikesir87** [comment]
The changes in #34 should make this a little bit better. I realized the image on Docker Hub didn't get updated. @StefanScherer - can you build and push an updated version of the image? I guess we should also get the auto-builds configured too.

**Comment by kosalanuwan** [comment]
Found the answer on a comment from another thread https://github.com/docker/getting-started/issues/29#issuecomment-627694003
I think the confusion was there are two getting started tutorials, 1) getting started image on docker hub that comes with a sample todo app, and 2) the  https://docs.docker.com/get-started/part2/ which uses another sample project. I was using the tutorial that came with the getting started image on docker hub.

**Comment by StefanScherer** [comment]
I've pushed a new image to Docker Hub.
