### ISSUE TITLE
sharing our app - play with docker step broken

### ISSUE THREAD

**Issue by markgoho** [docker/getting-started#131]
following the directions exactly, and after pushing my image to docker hub, then going to the Play with docker site and trying to start my freshly pushed app, I get:
``` bash
docker: Error response from daemon: error creating temporary lease: write /var/lib/docker/containerd/daemon/io.containerd.metadata.v1.bolt/meta.db: no space left on device: unknown.
```

upon trying the command again, I get:
``` bash
e95f33c60a64: Pull complete 
8ad47429afec: Extracting [====================================>              ]  17.83MB/24.6MB
ed32558722b1: Download complete 
b1f8c696047a: Download complete 
292a9c52fedf: Download complete 
daba973cad49: Download complete 
28301fdfb6ac: Downloading [==================================================>]  36.89MB/36.89MB
docker: write /var/lib/docker/tmp/GetImageBlob121549586: no space left on device.
```

I realize this is probably not a bug with the getting-started repo/instructions, but this is likely where people would come to see if others had this issue.

**Comment by mikesir87** [comment]
Hi @markgoho and apologies for the delay in responding to your issue. We're trying to clean things up and do better going forward!

Unfortunately, the issue you ran into with Play with Docker was an intermittent issue. It's been resolved, so I'm going to close this issue. But, let us know if you run into other issues in the future!
