### ISSUE TITLE
when getting-started/app/src/persistence/index.js is called in order to setup the persistence layer?

### ISSUE THREAD

**Issue by smoms** [docker/getting-started#132]
when getting-started/app/src/persistence/index.js is called in order to setup the persistence layer?

**Comment by mikesir87** [comment]
Hi @smoms! 👋  Apologies for it taking so long to get back to you too.

The `src/persistence/index.js` file is imported at the top of `src/index.js` with the line of code:

```js
const db = require('./persistence');
```

It's then used later on when running:

```js
db.init().then(() => {
...
});
```

Depending on the environment variables that are set, it'll change the implementation of the "db" that's imported. For each "db", there's an `init` function that's defined and is used to initialize that particular database type. 

I'm going to go ahead and close this issue as it's more of a discussion and not an issue about the project we need to fix. If you have more questions, feel free to keep the conversation going.
