### ISSUE TITLE
Permission denied on using-bind-mounts

### ISSUE THREAD

**Issue by toro-** [docker/getting-started#14]
Recently decided to try and find out more about containers and Dockers. Finding this tutorial well written, however I am finding some difficulty with the following command:
`docker run -dp 3000:3000 \`
`    -w /app -v $PWD:/app \`
`    node:12-alpine \`
`    sh -c "yarn install && yarn run dev"`

Docker creates an ID, check `docker ps` - nothing is running

Check `docker logs -f <ID>` and I see the that permission has been denied:
`yarn install v1.22.4`

`info No lockfile found.`

`[1/4] Resolving packages...`

`[2/4] Fetching packages...`

`[3/4] Linking dependencies...`

`[4/4] Building fresh packages...`

`error Could not write file "/app/yarn-error.log": "EACCES: permission denied, open '/app/yarn-error.log'"`

`error An unexpected error occurred: "EACCES: permission denied, mkdir '/app/node_modules'".`

`info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.`

I've been back over the tutorial a couple of times to ensure that I haven't missed a step and as far as I can tell, all steps have been followed.

Running this under Linux. If you need any info, let me know.

Thanks

**Comment by toro-** [comment]
I've tried again on Docker Playground and it appears to work flawlessly.

I've deleted all the files on my own machine and started again, still getting permissions error, but seems to be specifically related to package.json. I chmoded this to 777 (I know this is not what you should do, but this is for testing) and it still gives a permissions error.

Re-ran the command with sudo (I am not running this as a root user, but as a user with membership of the "docker" group), same error in `docker logs -f <ID>`

**Comment by toro-** [comment]
Some additional information: I have also tried running the command with the actual path instead of using $PWD in case that the variable was causing issues. It appears not to have mattered.

I am attempting to run this under CentOS 7.7 and I have also tried under ArchLinux and getting no where fast.

**Comment by mikesir87** [comment]
I'll admit I'm not as versed in the various linux distros, so forgive me if something is obvious. Kinda semi-sorta brain-dump/thinking going on here...

- The container is running as the `root` user
- Your filesystem is being mounted into the container
- The `root` user _should_ be able to access anything, as it is root. So, something is blocking the access.

To me, it sounds like an SELinux issue. Might want to look at [this StackOverflow answer](https://stackoverflow.com/a/31334443/502139) to see if it helps.

**Comment by toro-** [comment]
I must admit SELinux isn't something that  I had considered. 

Upon some digging in to it, I find ArchLinux doesn't support SELinux and it isn't active in my install.

It is, however, active in my CentOS install. I issued the command to temporarily make it permissive, but alas, the same error.

I'll continue looking in to it - I cannot imagine that I'm the only person to have come across similar issue.

**Comment by toro-** [comment]
I believe that I have solved it...at the very least I have it working on my Arch and CentOS installs.

Slight change to the command.

`docker run -dp 3000:3000 \
-w /app -v "$(pwd)":/app \
node:12-alpine \
sh -c "yarn install && yarn run dev"`

Note the change of `$PWD` to `"$(pwd)`.

Source of inspiration: Use bind mounts https://docs.docker.com/storage/bind-mounts/#start-a-container-with-a-bind-mount

Sorry couldn't get this to link for some reason.

**Comment by mikesir87** [comment]
Interesting. Is `$PWD` not defined in your shells? Your workaround works for, I believe, all Linux environments, but I do t think would work in PowerShell. This is one of the few times I can say, “I wish I had a Windows machine to test on.” 😆

**Comment by toro-** [comment]
If I do
`echo $PWD`
it returns the same as the `pwd` command. So I've no idea why it wasn't working.

I'll try to test on Windows machine tomorrow and let you know

**Comment by mikesir87** [comment]
Ok. What happens if you do the `docker run` with curly brackets around the PWD (`${PWD}:/app`)?

**Comment by toro-** [comment]
Using `${PWD}:/app`

 - in Linux:
  `/usr/bin/docker-current: Error response from daemon: invalid volume spec ":/app": invalid volume specification: ':/app'.
See '/usr/bin/docker-current run --help'.`

 - In Windows:
It runs without issue
_Side note_: Windows does not care if it is `{pwd}` or `{PWD}`

Using `"$(pwd)":/app`
- In Linux
It runs without issue

- In Windows:
`C:\Program Files\Docker\Docker\resources\bin\docker.exe: invalid reference format.`

**Comment by StefanScherer** [comment]
I'll update is that we should update to `-v "$(pwd):/app"` 
I've opened #70 to fix that.
