### ISSUE TITLE
Yarn issue across the tutorial - "yarn config set strict-ssl false -g"

### ISSUE THREAD

**Issue by gajjalaanvesh** [docker/getting-started#157]
I am new to Docker and started with the "getting-started" tutorial available. 

First issue faced after starting was with "yarn install", where it throws error with SSL certificate. 

Went through the Issues and was able to find a work around to it.

docker run -dp 3000:3000 `
-w /app -v "$(pwd):/app" `
node:12-alpine `
sh -c "**yarn config set strict-ssl false -g** && yarn install && yarn run dev"

<img width="726" alt="docker run error1" src="https://user-images.githubusercontent.com/84413264/119216997-d697ef00-baf4-11eb-8ed5-10ab441ac93c.PNG">

as we progress further this ssl certificate issue seems to be present at almost all the sections. When every I try to run a container I have to modify the commands given to have **"yarn config set strict-ssl false -g"** else I will have issue with container exiting immediately after creating.

Error below is seen when I run following command. 
**"docker run -dp 3000:3000 -v todo-db:/etc/todos getting-started"**

<img width="509" alt="Yarn SSL certificate issue0" src="https://user-images.githubusercontent.com/84413264/119217127-ad2b9300-baf5-11eb-9161-6674432de78e.PNG">

**Modified command:** (was successful)
docker run -dp 3000:3000 -w /app -v todo-db:/etc/todos getting-started sh -c **"yarn config set strict-ssl false -g** && yarn install && yarn run dev" 

<img width="726" alt="Yarn SSL certificate issue" src="https://user-images.githubusercontent.com/84413264/119217174-f4b21f00-baf5-11eb-84f8-0d5b25d43cea.PNG">

**Requirement:** 
There should be a permanent fix to this issue, instead of modifying the commands at every time to have "yarn config set strict-ssl false -g"
Would save lot of time for newbies like me

Cheers,
AKR

**Comment by mikesir87** [comment]
Thanks for the issue and apologies for the delayed response. 

Configuring the tutorial (or any other codebase) to not use strict SSL is a dangerous thing to do. SSL is important to not only encrypt network communication, but to help you have assurances that the remote party you are talking to is indeed the party you anticipate talking to. Therefore, if you are seeing certificate issues, it either means the remote party has a bad cert (expired, name mismatch) or that someone else is in your network path and trying to intercept your traffic (could be nefarious or not). In some corporate environments, they might have outbound network proxies that intercept all traffic, which will require additional SSL config for your apps to work correctly. Unfortunately, that's beyond the scope of our getting started tutorial (sorry!).

**Comment by charith9422** [comment]
Use "yarn config set enableStrictSsl false" instead of "yarn config set strict-ssl false -g"
