### ISSUE TITLE
localhost:80 always points to Docker getting started page even when no containers are runnning

### ISSUE THREAD

**Issue by danre07** [docker/getting-started#166]
I'm new to docker and I'm trying to make an app and have it point to port 80. Port 80 always takes me Docker's getting started page (nothing listed under `docker ps -a`).

Should I take this to mean that port 80 is off limits now that I've installed Docker? I've not read anything online about this and was wondering what I should do here.

It seems another user is having the exact same problem, but the answers provided don't solve the problem: 
https://stackoverflow.com/questions/64383254/docker-port-localhost80-is-always-listened-on

**Comment by ShivanshSharma1** [comment]
Use `docker container ls -a` and see if there is any active container

**Comment by mikesir87** [comment]
When a container that has an exposed port is stopped, that port is released and is no longer being listened to by Docker. On very rare circumstances, I've run into issues where a container wasn't cleaned up properly, but a restart of Docker Desktop fixed that.

What's most likely happening is your browser has a cached copy of the app and when you're opening http://localhost, it's automatically loading that cached copy. To test this, you can open an Incognito/Private window and try loading the site. You should then see it no longer loads the app (assuming the container isn't running).

If you run into further issues, feel free to let us know and we'll be happy to help investigate.
