### ISSUE TITLE
Play-With-Docker instance capacity exceeded with getting-started container

### ISSUE THREAD

**Issue by cquoss** [docker/getting-started#168]
When trying to run the getting-started container in play-with-docker as suggested in the 'Sharing Our App' section of the tutorial, this leads to the following error:
$ docker run -dp 3000:3000 cquoss/getting-started
Unable to find image 'cquoss/getting-started:latest' locally
latest: Pulling from cquoss/getting-started
ddad3d7c1e96: Pull complete 
8bb195d94de4: Pull complete 
be9b379f7fa3: Pull complete 
3b8a9bc999d9: Pull complete 
0f00e1dbd565: Extracting [==================================================>]  70.03MB/70.03MB
c7ee1489da85: Download complete 
e3b5d8ee54b9: Download complete 
68f92768b704: Download complete 
docker: failed to register layer: Error processing tar file(exit status 1): write /usr/libexec/gcc/x86_64-alpine-linux-musl/9.3.0/cc1: no space left on device.
See 'docker run --help'.

**Comment by SunyataZero** [comment]
Same here, i was following the docker tutorial

**Comment by jules946** [comment]
Hi, I received a similar error today: 
![image](https://user-images.githubusercontent.com/114394404/200361323-ddbe04db-cf33-4dcc-a462-ac103507d12e.png)

**Comment by mikesir87** [comment]
As this is an intermittent issue, I'm going to close this. If it comes up again, feel free to create a new issue.
