### ISSUE TITLE
Persist-the-DB: Where is '/etc/todos/todo.db' ?

### ISSUE THREAD

**Issue by MichaelSodeke** [docker/getting-started#180]
Background
---
Hello, I was following this tutorial: [docker-getting-started](https://docs.docker.com/get-started/05_persisting_data/) and got stuck on *Part-5: Persist the DB*.

After cloning the getting-started repo: `git clone https://github.com/docker/getting-started.git`, extracting the app directory: `mv getting-started/app ./; rm -rf getting-started`, creating the Dockerfile: `nano Dockerfile`, and building the container inside the app: `docker build -t getting-started .`, I got stuck reading this passage, quote: *"By default, the todo app stores its data in a **SQLite Database** at `/etc/todos/todo.db`"*.

I checked in my `/etc` file but was unable to find `/etc/todos` file. I also checked `package.json`, which did include *mysql* and *sqlite*.

Question
---
Why am I unable to find `etc/todos` directory?

System Info
---
```
$ cat /etc/os-release

PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by publinchi** [comment]
1. Finds the name of the container that starts the todo-app application. ie: docker ps | grep 3000
2. Enter the container with the name you found in point 1: ie: docker exec -it dreamy_matsumoto sh
3. once inside the container, check the files in: ls -ltr /etc/todos/
   total 8
   -rw-r--r--    1 root     root          8192 Aug 29 19:59 todo.db
4. voila

**Comment by MichaelSodeke** [comment]
> 
> 
>     1. Finds the name of the container that starts the todo-app application. ie: docker ps | grep 3000
> 
>     2. Enter the container with the name you found in point 1: ie: docker exec -it dreamy_matsumoto sh
> 
>     3. once inside the container, check the files in: ls -ltr /etc/todos/
>        total 8
>        -rw-r--r--    1 root     root          8192 Aug 29 19:59 todo.db
> 
>     4. voila

I was unaware that containers were Linux distros. The steps provided by @publinchi are critical for beginners and should be included in the tutorial. Thanks again @publinchi for pointing this out to me. I will head over and propose changes to `docker.github.io/get-started/05_persisting_data.md`.
