### ISSUE TITLE
Sharing our app: Running in Play with Docker doesn't work

### ISSUE THREAD

**Issue by bviala** [docker/getting-started#197]
After the run command, no 3000 badge show up, and if I open port manually, the page shows:  
```
This page isn’t working  
ip172-18-0-31-c56htqvnjsv000aahgl0-3000.direct.labs.play-with-docker.com didn’t send any data.
ERR_EMPTY_RESPONSE
```

The run command itself issues this warning:  
`WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested`  
  
I tried to use the `--platform` option, no luck

I'm using a M1 macbook

**Comment by bviala** [comment]
- Easy solution: force linux platform when building, by using the platform tag in the Dockerfile:

`FROM --platform=linux/amd64 node:12-alpine`

Your M1 mac will still be able to run the image, but with an emulation layer
doc: https://docs.docker.com/engine/reference/builder/#from

- Better solution: use buildx to build a multi-arch image https://docs.docker.com/desktop/multi-arch/

**Comment by muescha** [comment]
this should be noted somehow in the tutorial before uploading it to play-with-docker.com

**Comment by muescha** [comment]
at least we should add a link to this issue here?

**Comment by muescha** [comment]
i created a PR #289 `update sharing-your-app for M1 users`
