### ISSUE TITLE
getting started script don't work

### ISSUE THREAD

**Issue by toutpuissantged** [docker/getting-started#210]
I installed the docker office software and set everything up in vscode as indicated in the tutorial but when I run the docker build it does not work

**Comment by Shawn1874** [comment]
What specifically didn't work?  I think that without more details of the specific steps taken, or console I/O text, or error messages I don't see how anyone could help resolve this.

**Comment by mikesir87** [comment]
Going to close this now, but feel free to open a new issue if you still need help. We've just published several updates which should help resolve issues others might have run into.
