### ISSUE TITLE
Step 2 of tutorial not working (docker build)

### ISSUE THREAD

**Issue by KyeDon** [docker/getting-started#217]
As per the below screenshot I'm stuck at the second step of the tutorial where you run the build command.
![image](https://user-images.githubusercontent.com/47357003/141110875-7a67888a-f741-4391-adcd-6a212a28adbd.png)

I'm running my PowerShell prompt as Admin. Any insight would be great.

**Comment by StefanScherer** [comment]
Thanks @KyeDon for reporting this. I'm already working on a fix in #218.

**Comment by StefanScherer** [comment]
As a minimal fix you can change `python` to `python3` to make the build work.

**Comment by KyeDon** [comment]
I've just seen that #215 also addresses this. Thanks for the response.
