### ISSUE TITLE
"docker build -t getting-started ." failed

### ISSUE THREAD

**Issue by brut0** [docker/getting-started#221]
I am doing the tutorial part Using Docker Compose on Windows 10 20H2.

I `run docker build -t getting-started .`  on step 2 "Our Application"
After thisI get the following error:

```
[+] Building 2.1s (6/8)
 => [internal] load build definition from Dockerfile                                                              0.0s 
 => => transferring dockerfile: 141B                                                                              0.0s 
 => [internal] load .dockerignore                                                                                 0.0s 
 => => transferring context: 2B                                                                                   0.0s 
 => [internal] load metadata for docker.io/library/node:12-alpine                                                 0.0s 
 => [1/4] FROM docker.io/library/node:12-alpine                                                                   0.0s 
 => ERROR [internal] load build context                                                                           2.0s 
 => => transferring context: 15.75MB                                                                              2.0s 
 => CACHED [2/4] WORKDIR /app                                                                                     0.0s 
------
 > [internal] load build context:
------
error from sender: open node_modules\type-check\lib: Access is denied`
```

If I disable buildkit, I get an error:
`error checking context: 'can't stat '\\?\C:\Users\getting-started\app\node_modules\type-check\lib''.`

I tried to clear build cache `docker builder prune` and it didn't help

**Comment by brut0** [comment]
If I disable buildkit, I get an error:
`error checking context: 'can't stat '\\?\C:\Users\getting-started\app\node_modules\type-check\lib''.`

**Comment by brut0** [comment]
I tried to clear build cache `docker builder prune` and it didn't help

**Comment by mikesir87** [comment]
Hi @brut0! Thanks for sharing your issue. We recognize it's been a long time since you posted this issue (sorry about that!), so it's quite likely you've moved on since then. But, before closing this issue, figured we'd check in first. Is it still an issue or do you still need help?
