### ISSUE TITLE
Step: "Building the App's Container Image" fails: executor failed running [/bin/sh -c yarn install]:

### ISSUE THREAD

**Issue by Leo-zryan** [docker/getting-started#224]
I'm working on Windows10 and close to no experience with docker whatsoever.

While working through the tutorial I ran into problems on the step described below:

I installed the Docker Desktop successfully and this works fine. The "Part1: Getting started" tutorial works as expected. But when I follow the "Part2: Sample application" and run the  "docker build -t getting-started . " command I get the following error:

`C:\Leo\Study\docker\getting-started-master\app>docker build -t getting-started .
[+] Building 9.3s (12/16)
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 251B                                                                               0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 2B                                                                                    0.0s
 => resolve image config for docker.io/docker/dockerfile:1                                                         4.2s
 => [auth] docker/dockerfile:pull token for registry-1.docker.io                                                   0.0s
 => CACHED docker-image://docker.io/docker/dockerfile:1@sha256:42399d4635eddd7a9b8a24be879d2f9a930d0ed040a61324cf  0.0s
 => [internal] load build definition from Dockerfile                                                               0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => [internal] load metadata for docker.io/arm64v8/node:12-alpine                                                  2.7s
 => [auth] arm64v8/node:pull token for registry-1.docker.io                                                        0.0s
 => [internal] load build context                                                                                  0.3s
 => => transferring context: 4.61MB                                                                                0.3s
 => CACHED [1/6] FROM docker.io/arm64v8/node:12-alpine@sha256:81fd09201bc661337e8e24413d9d1fd87a77f000db567c589ae  0.0s
 => ERROR [2/6] RUN apk add --no-cache python2 g++ make                                                            2.1s
------
 > [2/6] RUN apk add --no-cache python2 g++ make:
#11 0.453 fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/aarch64/APKINDEX.tar.gz
#11 1.481 365098232904:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1914:
#11 1.491 WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.14/main: Permission denied
#11 1.491 fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/aarch64/APKINDEX.tar.gz
#11 2.058 365098232904:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1914:
#11 2.063 WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.14/community: Permission denied
#11 2.069 ERROR: unable to select packages:
#11 2.077   g++ (no such package):
#11 2.077     required by: world[g++]
#11 2.077   make (no such package):
#11 2.077     required by: world[make]
#11 2.077   python2 (no such package):
#11 2.077     required by: world[python2]
------
executor failed running [/bin/sh -c apk add --no-cache python2 g++ make]: exit code: 3

[+] Building 71.3s (13/13) FINISHED
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 210B                                                                               0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 2B                                                                                    0.0s
 => resolve image config for docker.io/docker/dockerfile:1                                                         1.9s
 => CACHED docker-image://docker.io/docker/dockerfile:1@sha256:42399d4635eddd7a9b8a24be879d2f9a930d0ed040a61324cf  0.0s
 => [internal] load build definition from Dockerfile                                                               0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => [internal] load metadata for docker.io/arm64v8/node:12-alpine                                                  2.0s
 => [internal] load build context                                                                                  0.0s
 => => transferring context: 2.67kB                                                                                0.0s
 => [1/5] FROM docker.io/arm64v8/node:12-alpine@sha256:81fd09201bc661337e8e24413d9d1fd87a77f000db567c589ae4f30414  0.0s
 => CACHED [2/5] WORKDIR /app                                                                                      0.0s
 => CACHED [3/5] COPY . .                                                                                          0.0s
 => CACHED [4/5] RUN yarn config set strict-ssl false -g                                                           0.0s
 => ERROR [5/5] RUN yarn install                                                                                  67.3s
------
 > [5/5] RUN yarn install:
#13 2.119 yarn install v1.22.15
#13 3.060 [1/4] Resolving packages...
#13 5.661 warning Resolution field "ansi-regex@5.0.1" is incompatible with requested version "ansi-regex@^2.0.0"
#13 5.687 warning Resolution field "ansi-regex@5.0.1" is incompatible with requested version "ansi-regex@^3.0.0"
#13 7.200 warning sqlite3 > node-gyp > tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
#13 7.505 warning sqlite3 > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
#13 7.923 warning sqlite3 > node-gyp > request > har-validator@5.1.5: this library is no longer supported
#13 8.156 warning sqlite3 > node-gyp > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
#13 10.74 [2/4] Fetching packages...
#13 47.64 info fsevents@2.3.2: The platform "linux" is incompatible with this module.
#13 47.66 info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
#13 48.15 [3/4] Linking dependencies...
#13 58.23 [4/4] Building fresh packages...
#13 67.05 error /app/node_modules/sqlite3: Command failed.
#13 67.05 Exit code: 1
#13 67.05 Command: node-pre-gyp install --fallback-to-build
#13 67.05 Arguments:
#13 67.05 Directory: /app/node_modules/sqlite3
#13 67.05 Output:
#13 67.05 node-pre-gyp info it worked if it ends with ok
#13 67.05 node-pre-gyp info using node-pre-gyp@0.11.0
#13 67.05 node-pre-gyp info using node@12.22.7 | linux | arm64
#13 67.05 node-pre-gyp WARN Using request for node-pre-gyp https download
#13 67.05 node-pre-gyp info check checked for "/app/node_modules/sqlite3/lib/binding/napi-v3-linux-arm64/node_sqlite3.node" (not found)
#13 67.05 node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v5.0.2/napi-v3-linux-arm64.tar.gz
#13 67.05 node-pre-gyp WARN Pre-built binaries not installable for sqlite3@5.0.2 and node@12.22.7 (node-v72 ABI, musl) (falling back to source compile with node-gyp)
#13 67.05 node-pre-gyp WARN Hit error self signed certificate in certificate chain
#13 67.05 gyp info it worked if it ends with ok
#13 67.05 gyp info using node-gyp@3.8.0
#13 67.05 gyp info using node@12.22.7 | linux | arm64
#13 67.05 gyp info ok
#13 67.05 gyp info it worked if it ends with ok
#13 67.05 gyp info using node-gyp@3.8.0
#13 67.05 gyp info using node@12.22.7 | linux | arm64
#13 67.05 gyp ERR! configure error
#13 67.05 gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
#13 67.05 gyp ERR! stack     at PythonFinder.failNoPython (/app/node_modules/node-gyp/lib/configure.js:484:19)
#13 67.05 gyp ERR! stack     at PythonFinder.<anonymous> (/app/node_modules/node-gyp/lib/configure.js:406:16)
#13 67.05 gyp ERR! stack     at F (/app/node_modules/which/which.js:68:16)
#13 67.05 gyp ERR! stack     at E (/app/node_modules/which/which.js:80:29)
#13 67.05 gyp ERR! stack     at /app/node_modules/which/which.js:89:16
#13 67.05 gyp ERR! stack     at /app/node_modules/isexe/index.js:42:5
#13 67.05 gyp ERR! stack     at /app/node_modules/isexe/mode.js:8:5
#13 67.05 gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:168:21)
#13 67.05 gyp ERR! System Linux 5.10.16.3-microsoft-standard-WSL2
#13 67.05 gyp ERR! command "/usr/local/bin/node" "/app/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/app/node_modules/sqlite3/lib/binding/napi-v3-linux-arm64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/app/node_modules/sqlite3/lib/binding/napi-v3-linux-arm64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
#13 67.05 gyp ERR! cwd /app/node_modules/sqlite3
#13 67.05 gyp ERR! node -v v12.22.7
#13 67.05 gyp ERR! node-gyp -v v3.8.0
#13 67.05 gyp ERR! not ok
#13 67.05 node-pre-gyp ERR! build error
#13 67.05 node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /app/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/app/node_modules/sqlite3/lib/binding/napi-v3-linux-arm64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/app/node_modules/sqlite3/lib/binding/napi-v3-linux-arm64 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
#13 67.05 node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/app/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
#13 67.05 node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
#13 67.05 node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1022:16)
#13 67.05 node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
#13 67.05 node-pre-gyp ERR! System Linux 5.10.16.3-microsoft-standard-WSL2
#13 67.05 node-pre-gyp ERR! command "/usr/local/bin/node" "/app/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
#13 67.05 node-pre-gyp ERR! cwd /app/node_modules/sqlite3
#13 67.05 node-pre-gyp ERR! node -v v12.22.7
#13 67.05 node-pre-gyp ERR! node-pre-gyp -v v0.11.0
#13 67.05 node-pre-gyp ERR! not ok
#13 67.05 Failed to execute '/usr/local/bin/node /app/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/app/node_modules/sqlite3/lib/binding/napi-v3-linux-arm64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/app/node_modules/sqlite3/lib/binding/napi-v3-linux-arm64 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
#13 67.05 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
------
executor failed running [/bin/sh -c yarn install]: exit code: 1
`

Since my computer is a windows10 ring, I did not add the "put" commandThe contents of my DockerFile as follows:

`# syntax=docker/dockerfile:1
FROM arm64v8/node:12-alpine
WORKDIR /app
COPY . .
RUN yarn config set strict-ssl false -g 
RUN yarn install
CMD ["node", "src/index.js"]`

I hope someone can solve this problem. Thank you.

**Comment by mikesir87** [comment]
Hi @Leo-zryan! 👋  Major apologies for the delay in responding to this issue. We recognize this issue is fairly old, so you all have most likely moved on a long time ago. Both our guide and Docker Desktop have improved a lot recently, many of which changes have hopefully resolved the issue you were experiencing. Therefore, we're going to go ahead and close out this issue. 

If you're still having issues, feel free to create a new issue and we can help you out going forward.
