### ISSUE TITLE
command in the "Bind Mounts"

### ISSUE THREAD

**Issue by zqcccc** [docker/getting-started#23]
![image](https://user-images.githubusercontent.com/19168323/81554483-75a1eb00-93b9-11ea-8939-f205bca24715.png)
When I run the command in the "Bind Mounts" section of this tutorial, it occurred errors. What should I do?

**Comment by mikesir87** [comment]
Hi @zqcccc! The problem here is the multi-line command. PowerShell doesn’t use the backslash to support multi-line commands, so we should do something to better support copy/paste. In the meantime, write out the command in a single line and it should work for you. Sorry about that!

**Comment by zqcccc** [comment]
Thanks! it worked. This tutorial is very nice for me.
