### ISSUE TITLE
Updating our App: Reminder to stop and/or remove the 2nd, port 3000 image

### ISSUE THREAD

**Issue by blitmap** [docker/getting-started#24]
Hello!

I'm working through these exercises right now as someone new to docker.

At the end of "Updating our App", it would be good to have a reminder telling the user to stop the 2nd, port 3000 image and then potentially remove it.  I forgot this and it does not seem like this image is re-used in later exercises.

(still getting to the finish)

**Comment by blitmap** [comment]
In this section you start `getting-started` reachable on port 3000.  You then stop this image, update the app, and start the new image on port 3000 again.  My initial issue is saying there should be a reminder to stop and `rm` the 2nd port 3000 image.

It occurs to me you were never advised to stop & rm the port 80 image from the previous section.

It would make sense to me to have a friendly reminder at the bottom of this section to stop both of these.  You wouldn't put a reminder in the previous section because you don't learn about stopping images until this one.

**Comment by StefanScherer** [comment]
Thanks @blitmap. Good catch.

I've created PR #35 to add a step to remove the todo app container before starting it with the persistent volume.
