### ISSUE TITLE
Typo in Markdown

### ISSUE THREAD

**Issue by Oranggge** [docker/getting-started#245]
There is mistake in markdown of code. It's look like this- 
![Screenshot_2022-02-13-28_794x382](https://user-images.githubusercontent.com/63722098/153778426-e3a40def-5846-4273-bcf5-58ce03605993.png)

**Comment by Isumairuu** [comment]
Another typo in the Multi-Container Apps part:
<img width="719" alt="image" src="https://user-images.githubusercontent.com/41214477/158073999-065c043a-9770-4d95-96d4-f153faa22703.png">

**Comment by mikesir87** [comment]
These have been resolved. Thanks!
