### ISSUE TITLE
Sharing our App: Re-tag, then login to Docker Hub - not before it is necessary

### ISSUE THREAD

**Issue by blitmap** [docker/getting-started#25]
Hello!

I am new to docker and working through these examples currently (in another tab).  In the Sharing our App section I became confused.

It asks you to login to Docker Hub _before_ re-tagging the `getting-started` image to use your Hub username.

**This made me believe you needed to be logged in to re-tag an image.**

 `docker tag` is a local operation.  You can re-tag an image to any name you like, but you would be prevented from pushing if you are not the repository owner.

I am suggesting putting the `docker login` command immediately before the `docker push`, not before the `docker tag`

From this:

> 2. Login to the Docker Hub using the command docker login -u YOUR-USER-NAME.
>
> 3. Use the docker tag command to give the getting-started image a new name. Be sure to swap out YOUR-USER-NAME with your Docker ID.
>
> > docker tag getting-started YOUR-USER-NAME/getting-started
>
> 4. Now try your push command again. If you're copying the value from Docker Hub, you can drop the tagname portion, as we didn't add a tag to the image name. If you don't specify a tag, Docker will use a tag called latest.
>
> > docker push YOUR-USER-NAME/getting-started

To this:

> 2. Use the docker tag command to give the getting-started image a new name. Be sure to swap out YOUR-USER-NAME with your Docker ID.
>
> > docker tag getting-started YOUR-USER-NAME/getting-started
>
> 3. Login to the Docker Hub using the command docker login -u YOUR-USER-NAME.
>
> 4. Now try your push command again. If you're copying the value from Docker Hub, you can drop the tagname portion, as we didn't add a tag to the image name. If you don't specify a tag, Docker will use a tag called latest.
>
> > docker push YOUR-USER-NAME/getting-started

**Comment by StefanScherer** [comment]
Hi @blitmap.
You're correct, the `docker tag` is a local command. But we've decided to keep the order of the commands.
A general recommendation is to be logged in to Docker Hub to get the best experience, even for building and pulling images.
