### ISSUE TITLE
Bug in formatting of Multi-Container Apps section

### ISSUE THREAD

**Issue by rockboynton** [docker/getting-started#258]
In http://localhost/tutorial/multi-container-apps/ 

See image for formatting bug of the note
![image](https://user-images.githubusercontent.com/32227280/160295279-6c77e3cc-4a61-4ed0-b5de-a53e6504050a.png)

**Comment by Umka-Deeplay** [comment]
And one more in section "Running our App with MySQL"...
In http://localhost/tutorial/multi-container-apps/

See image for formatting bug of the note
![image](https://user-images.githubusercontent.com/93371979/160662680-32b54d4d-6da1-4f18-a18e-cd5587f717e7.png)

**Comment by Umka-Deeplay** [comment]
Fixed in PullRequest https://github.com/docker/getting-started/pull/255
