### ISSUE TITLE
Persisting our DB:  Is there a better way to keep a container from exiting?

### ISSUE THREAD

**Issue by blitmap** [docker/getting-started#26]
In this section it is demonstrated that 2 separate instances of the same image do not share files.  You are instructed to run:

> `docker run -d ubuntu bash -c "shuf -i 1-10000 -n 1 -o /data.txt && tail -f /dev/null"`

This seemed odd.  I was reminded of when I first started programming and I was taught several different ways to keep a program running (like the above), and others using `sleep()` or even a busy for-loop.  They all have their problems.

I went Googling and there are several ways this is being done by the community.  I could not find *The Right Answer*.  Is there an official, recommended way to keep a container running?  This one relies on having `tail` available.

I think this could be improved because it otherwise instills 1 way as "The Way" for people who are very new to Docker.

(me)

**Comment by mikesir87** [comment]
Great question and apologies for the super long delay in responding to you. 

To answer the question, there are a variety of ways to keep a container running. At the end of the day, a container runs as long as its main process is still running. So, using `tail -f /dev/null` is quite common (or tail'ing any other file). So, no... there's no "1 way" to do it, but it is pretty common. Hope that helps!
