### ISSUE TITLE
how to download multiple private repository in docker?

### ISSUE THREAD

**Issue by mrajancsr** [docker/getting-started#263]
Hello, i have an issue where i need to download multiple private repositories into docker container.  I raised this over here: 
https://stackoverflow.com/questions/71722564/how-to-download-multiple-private-repositories-in-docker?noredirect=1#comment126752746_71722564

I'm not able to understand how one does a git clone of multiple private repos.  My current config file: 

Host dbreader
   Hostname github.com
   User git
   IdentityFile=/Users/raj/.ssh/id_rsa

Host trading-engine
   Hostname github.com
   User git
   IdentityFile=/Users/raj/.ssh/id_rsa_docker
   
   Do i copy over my config file in ssh over to docker? 
   
   My current docker configuration:
   
FROM python:3.9

# create a folder and cd into it
run mkdir temp_repo
run cd temp_repo

# set folder as current working directory
workdir /temp_repo

# move hello_world.py script from our local system to current workdir in docker
add hello_world.py .

# copy the requirements file from current system to docker directory
copy requirements.txt .
run pip install -r requirements.txt
copy . /temp_repo

RUN mkdir -p -m 0600 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
RUN --mount=type=ssh pip install git+ssh://git@github.com/moon_research/dbreader.git
RUN --mount=type=ssh git clone git+ssh://git@github.com/moon_research/dbreader.git
RUN --mount=type=ssh pip install git+ssh://git@github.com/moon_research/trading-engine.git
copy timescale.pem /root

run apt-get update -y

cmd ["python", "-u", "hello_world.py"]

It fails in this step: RUN --mount=type=ssh pip install git+ssh://git@github.com/moon_research/trading-engine.git

Thanks

**Comment by mikesir87** [comment]
Hi there! Thanks for sharing your issue with us. Unfortunately, this repo is intended to provide support for only the getting-started guide. If you still need assistance, feel free to post on the [forums](https://forums.docker.com) or join us in the [Docker Community Slack](https://dockr.ly/comm-slack).
