### ISSUE TITLE
docker build -t getting-started .  failed

### ISSUE THREAD

**Issue by Jamesmahaitao** [docker/getting-started#277]
OS: MacBook Pro (13-inch, M1, 2020)
when i follow https://docs.docker.com/get-started/02_our_app/ to learn build the app’s container image.
type docker build -t getting-started . on terminal，and occur the error:
![1](https://user-images.githubusercontent.com/17718184/168617609-e089ba01-8e5e-440a-953c-b26d202cab6b.png)
in this time,my dockerfile is :
![image](https://user-images.githubusercontent.com/17718184/168617888-878cc6c9-c32a-4056-988f-1982dd8d07b9.png)
and change  `RUN apk add --no-cache python2` to `RUN apk add --no-cache python3`
the error changed:
![image](https://user-images.githubusercontent.com/17718184/168618371-392775b6-8273-492b-a4fa-006945decbe0.png)

i don't kown how to solve it,I would appreciate your assistance with this matter

**Comment by Gohoy** [comment]
Have you solved it? I'm having the same problem

**Comment by Jamesmahaitao** [comment]
> Have you solved it? I'm having the same problem

NO, it's hard to solve

**Comment by Gohoy** [comment]
I've solved that this could be a network problem

**Comment by Gohoy** [comment]
> 

I've solved that this could be a network problem

**Comment by Jamesmahaitao** [comment]
> > 
> 
> I've solved that this could be a network problem

what have you done?
Is your MacBook an M1 chip?

**Comment by Gohoy** [comment]
> > > 
> > 
> > 
> > I've solved that this could be a network problem
> 
> what have you done? Is your MacBook an M1 chip?

Oh ，I use Windows.
I just used a better VPN,  rebuild ,and it executed successfully

**Comment by GabrielSousa02** [comment]
@Jamesmahaitao Are you still facing the issue?

I ran the code here and it worked. I manually typed your `Dockerfile`:
```docker
FROM node:12-alpine
RUN apk add --no-cache python2 g++ make
WORKDIR /app
COPY . .
RUN yarn install --production
CMD ["node", "src/index.js"]
EXPOSE 300
```

I use a MacPro M1, and the built went through.

<img width="1496" alt="Screen Shot 2022-06-03 at 12 42 40 AM" src="https://user-images.githubusercontent.com/10780289/171781765-9503e0fd-1fff-445a-b147-9294e36a5d05.png">

- What I would suggest is:
    1. How did you install Docker? If you used the Docker Desktop client, maybe it's worth updating it.
    2. After updating your Docker, I would recommend deleting your img, and building it again:
    `docker image rm getting-started`
    3. Another thing would be copy & pasting the Dockerfile info from the tutorial's page, just in case there's any typo on your own file.
    4. One last option, based on the comment made by Gohoy, is to verify that you have a stable connection, because the `node:12-alpine` image will update it's packages and it performes a few downloads.

Let me know if you had any progress.

**Comment by kaishibianchengqiji12** [comment]
Have you solved it? I'm having the same problem

**Comment by kaishibianchengqiji12** [comment]
very slow

**Comment by kaishibianchengqiji12** [comment]
2021 app mi pro

**Comment by Jamesmahaitao** [comment]
> 

Thank you so much for your reply, i update my Docker desktop to 4.9.0(80466),and then run docker build -t getting-started . again，it works.

Dockerfile:
![image](https://user-images.githubusercontent.com/17718184/174647099-06f5c5f5-df3f-4e86-a765-c05e823acd90.png)

**Comment by Jamesmahaitao** [comment]
> @Jamesmahaitao Are you still facing the issue?
> 
> I ran the code here and it worked. I manually typed your `Dockerfile`:
> 
> ```
> FROM node:12-alpine
> RUN apk add --no-cache python2 g++ make
> WORKDIR /app
> COPY . .
> RUN yarn install --production
> CMD ["node", "src/index.js"]
> EXPOSE 300
> ```
> 
> I use a MacPro M1, and the built went through.
> 
> <img alt="Screen Shot 2022-06-03 at 12 42 40 AM" width="1496" src="https://user-images.githubusercontent.com/10780289/171781765-9503e0fd-1fff-445a-b147-9294e36a5d05.png">
> 
> * What I would suggest is:
>   
>   1. How did you install Docker? If you used the Docker Desktop client, maybe it's worth updating it.
>   2. After updating your Docker, I would recommend deleting your img, and building it again:
>      `docker image rm getting-started`
>   3. Another thing would be copy & pasting the Dockerfile info from the tutorial's page, just in case there's any typo on your own file.
>   4. One last option, based on the comment made by Gohoy, is to verify that you have a stable connection, because the `node:12-alpine` image will update it's packages and it performes a few downloads.
> 
> Let me know if you had any progress.

Thank you so much for your reply,  I update my Docker desktop to 4.9.0(80466), and then run docker build -t getting-started . again, it works.
Dockerfile:
![image](https://user-images.githubusercontent.com/17718184/174647575-36216285-72a1-4870-b68e-8327ef397e4f.png)
