### ISSUE TITLE
Using Bind Mounts: "Make sure you don't have any previous getting-started containers running."

### ISSUE THREAD

**Issue by blitmap** [docker/getting-started#28]
In "Using Bind Mounts" this line could be improved:

"Make sure you don't have any previous getting-started containers running."

If you stop/remove all previous getting-started containers you would kill the documentation you're reading from (`docker/getting-started`).

"Make sure the only container you have running is: docker/getting-started"

Better?

**Comment by kral2** [comment]
"Make sure you don't have any previous getting-started containers running." refers to the image name. The documentation should be from "docker101tutorial" image.

But I agree that it is confusing, and this section may need to be rephrased for more clarity

**Comment by StefanScherer** [comment]
Thanks for the suggestions. The tutorial can be started in two different ways leading to different image names.
I agree that needs more clarification.

**Comment by diligent176** [comment]
This relates to my Issue #114 

It's very strange that we tag the getting-started image as "docker101tutorial" and then tag our To-Do application image as "getting-started"...  This really should be changed.  At the very least, tag the application something other than getting-started, which is the name of this tutorial's image.   Uuugh.

https://github.com/docker/getting-started/issues/114
