### ISSUE TITLE
Getting-started documentation confusing for beginners

### ISSUE THREAD

**Issue by nhamawi** [docker/getting-started#288]
Hi Guys,

I'm BRAND NEW to Docker and have installed Docker for Windows 10. When I run the following command, I get an error:

C:\STUFF>docker run -d -p 80:80 docker/getting-started
5ae64772806b2a25872883d65d25a06a627c3b042a0b620000d790f61ee42872
docker: Error response from daemon: Ports are not available: exposing port TCP 0.0.0.0:80 -> 0.0.0.0:0: listen tcp 0.0.0.0:80: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

While this fails, every time I run this, I see a new and very suspicious Container added to my Docker Desktop for Windows with someone else's name, such as show in the attached image (example: "beautiful_morse", and "fervent_wing"):

![image](https://user-images.githubusercontent.com/2650762/180496782-8af603ff-ac78-484f-ab03-7baa0871bb87.png)

As a new user, I'm thinking, "Did I just somehow download someone else's getting-started image? Could this be malicious? And where did this get downloaded to? I don't see any new folder with this image being created on my local system?"

Also, there is a README.md which suggests running the following with triple back-quotes (sorry if you're seeing the markup that is missing the "bash" command):

```bash
docker run -d -p 80:80 docker/getting-started
```

This does not seem to work in Windows as it appears to be running the command through a bash shell. Is this perhaps instructions for someone running Docker in Linux?

Regarding the instructions: "This project has a docker-compose.yml file, which will start the mkdocs application on your local machine and help you see changes instantly." What do you mean "see changes instantly"? See changes to what exactly?

Anyway, I was able to run the command "docker-compose up" which was the ONLY way I was able to run the documentation project and visit port 8000. However, the documentation congratulated me and reminded how I supposedly got there (by running docker run -d -p 80:80 docker/getting-started) but that was certainly not the case and not the same port either. I got there by running "docker-compose up". The suggested docker run command does not work for me as noted, and instead seems to download someone else's container.

So as you can see, for beginners, some likely very obvious things are not so obvious. My request is to give a few more details for beginners around the how-to and the expectations, and to note differences in instructions depending on whether using Linux as main OS vs Windows as the main OS.

Thank You

**Comment by alexjordan6** [comment]
It looks like you have some other process on your system using port 80. This was happening for me

the docker-compose up stuff is not for the beginner tutorial. It's for folks that want to modify/change the getting started tutorial itself - when it says you can see changes instantly that is referring to those folks that are working on the tutorial itself. 

Those are the names of the container instances - if you don't provide a name then docker will make one up for you, that's what you're seeing

**Comment by alexjordan6** [comment]
try `docker run -d -p 8080:80 docker/getting-started` then go to `http://localhost:8080`

**Comment by mikesir87** [comment]
Thanks all for the issue, comments, and feedback! It is greatly appreciated, despite the delay in getting back to you. We're working through our PR/issue queue and planning to do much better in responding in a more timely manner.

As was mentioned by @alexjordan6, you most likely had another process (maybe IIS?) running on port 80. That normally gives a different error, but it can vary. Did the `docker run -d -p 8080:80 docker/getting-started` work better for you?

As was also mentioned, the random-looking names are just that... random container identifiers. The image you pull and start (`docker/getting-started`) is used to start a container, each of which has their own unique ID. But, you do bring up a fantastic point that 1) we never really explain that and 2) that can be quite confusing to someone brand new to Docker.

With that in mind, we're taking a deep look at our onboarding and education material and looking at how we can make the experience easier and better, as we know the learning curve is quite massive and steep. So, if you have any more feedback, please, _please_ don't hesitate to share it! Thanks!

**Comment by mikesir87** [comment]
I'm going to go ahead and close this issue. Feel free to reopen/continue the conversation if you see fit. Again, we're planning on making the tutorial better in the near future. So... stay tuned!
