### ISSUE TITLE
Using Bind Mounts: Missing explanation for `-v` option

### ISSUE THREAD

**Issue by schegde** [docker/getting-started#30]
Hi,
   I was going through the tutorial, and for the `Using Bind Mounts` page, in `Starting a Dev-Mode Container`, I wasn't able to find a comment/explanation for `-v <path>`  argument for the command in Step 2. Would be nice to have its explanation included along with other arguments. 
Thanks!

**Comment by EfiGordon** [comment]
The meaning is for **volume**, they already changed it to `-v ${PWD}`, but still an extra explanation would be nice, also I am suggesting to add a comment that this would work only on Powershell for windows users (I had some trouble time trying this in cmd)

**Comment by EfiGordon** [comment]
And additionally, the command contains backslashes which not supported on Powershell, the command should be all in one line.

**Comment by Kezden** [comment]
Hello,
I am running the tutorial from VS Code, and I am getting an error "invalid reference format".
${PWD} looks like a variable that I should've defined before this command is run?
I fully understand what -v represents, but maybe provide an example of a defined path?
Great tutorial btw!

Thanks!

**Comment by StefanScherer** [comment]
@Kezden The `${PWD}` is a variable that is automatically set in a Mac terminal (eg. bash) or on Windows in a PowerShell terminal. `PWD` is the current working directory of the shell.
If it doesn't work for you, just type the absolute path of the current working directory instead.
