### ISSUE TITLE
Docker desktop tutorial

### ISSUE THREAD

**Issue by benblo** [docker/getting-started#305]
Hi! First-time Docker user here, just ran through the tutorial:
- got confused after the "clone the image" step, what did it actually do?
  - had an intuition this was gonna start a web server, what with Docker being "a cloud thing" (btw I'm not a webdev but a gamedev so I have no idea what I'm doing here)
  - ... but there actually weren't any instructions to open a web browser to check the result!
- went through the next steps (share etc), until the end, and poof the tutorial disappeared, again with no instructions as to what to do with all the things we'd just done! Felt like spewing commands and shuffling files around just for the sake of it, no purpose and no end result :/
- clicked around the interface blindly, found my image, clicked a link and bam got http://localhost/tutorial/, finally!
- OK so did I miss something here? let's run the tutorial again... oh wait there's no button in the UI to do that (despite [what this issue describes](https://github.com/docker/docs/issues/10823#issuecomment-629940905), no Learn menu for me)
- ... and now I actually look at the page, and figure out the rest of the tutorial is handed off to that app image we just created. Which makes sense, but again, so much confusion!

It could all be much clearer very easily, just one sentence at each step saying "here's what we're doing here, and the expected result". Which you know, maybe is actually there and I just skimmed through too fast to notice, but since I can't run it again, I can't know 😀 !

**Comment by mikesir87** [comment]
Hi there and thanks for the honest and open feedback! We apologize that it's taken a little while to get back to you too.

We just merged in quite a few updates, including bringing all of the screenshots, commands, images, and dependencies up-to-date to the current/latest versions. So, hopefully that will help with a few of the issues you mentioned.

We are taking a look at our overall onboarding and education setup as well, so all of your feedback is great to hear. If you have more, feel free to keep it coming! We know that learning Docker and containers has a large learning curve and want to make it easier. 😄
