### ISSUE TITLE
fsevents@1.2.9: The platform "linux" is incompatible with this module.

### ISSUE THREAD

**Issue by stevemclarke** [docker/getting-started#31]
On building the todo list app it appears there is an issue with the fsevents module when running on windows (containers in linux mode).

[2/4] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...

---additional information---
G:\Docker\DockerDesktop\TutorialApp\app>docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:23:10 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

G:\Docker\DockerDesktop\TutorialApp\app>systeminfo 
(redacted)
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.18362 N/A Build 18362
System Manufacturer:       Gigabyte Technology Co., Ltd.
System Model:              Z270M-D3H
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 94 Stepping 3 GenuineIntel ~4001 Mhz
BIOS Version:              American Megatrends Inc. F7, 16/11/2017
Total Physical Memory:     65,496 MB

G:\Docker\DockerDesktop\TutorialApp\app>

**Comment by mikesir87** [comment]
@stevemclarke - is this actually breaking the build for you? The failure of `fsevents` to install isn't actually a problem and can be safely ignored. When npm installs its dependencies, it tries to use this dependency to watch for file changes using filesystem events. If that module isn't available, it'll simply fall back to polling for file changes. So, yes... less optimal, but _should_ still work.

**Comment by stevemclarke** [comment]
@mikesir87 - no it's not breaking lol, it's an error/warning that's showing.  Noting it's a tutorial for new users of docker, it stands out.  If it's a common library that would normally be present, then a note in the tutorial guide would suffice to point out the warning may occur (might be worth putting one in about the permissions warning as well).

**Comment by corneliusroemer** [comment]
Getting the same warning, not breaking the build, but would be nice to include a note, since this is the only error message I get.

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.4
BuildVersion:	19E287

$ docker --version
Docker version 19.03.8, build afacb8b

**Comment by StefanScherer** [comment]
Good catch. The `fsevents` module is an optional dependency. You can ignore that warning.
