### ISSUE TITLE
docker build -t getting-started .  produces error with yarn in ssl-strict false.

### ISSUE THREAD

**Issue by hutchd2005-code** [docker/getting-started#315]
Dockerfile contains following
FROM arm64v8/node:12.12-alpine 
WORKDIR /app 
COPY . . 
RUN apk add --no-cache python2 g++ make
RUN yarn config set strict-ssl false -g 
RUN yarn install --production
CMD ["node", "src/index.js"]

> [6/6] RUN yarn install --production:
#10 1.716 yarn install v1.19.1
#10 2.501 [1/4] Resolving packages...
#10 3.083 warning Resolution field "ansi-regex@5.0.1" is incompatible with requested version "ansi-regex@^2.0.0"
#10 3.129 warning Resolution field "ansi-regex@5.0.1" is incompatible with requested version "ansi-regex@^3.0.0"
#10 4.219 [2/4] Fetching packages...
#10 52.53 error jest@27.2.5: The engine "node" is incompatible with this module. Expected version "^10.13.0 || ^12.13.0 || ^14.15.0 || >=15.0.0". Got "12.12.0"
#10 52.58 error Found incompatible module.
#10 52.58 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
------
executor failed running [/bin/sh -c yarn install --production]: exit code: 1
PS H:\getting-started\app>

**Comment by mikesir87** [comment]
It looks like you're doing something that's not part of our tutorial, but we can try to help out. Looking at the error message you're getting, the version of Jest you're trying to use isn't compatible with the version of Node you're using. So, either update Node to a newer version or rollback Jest to an older version.

FWIW... we just merged in quite a few updates to have the app use the latest versions of Node, Jest, etc. The image is still building and being deployed, but you might want to give that a try and see if it helps at all.

**Comment by hutchd2005-code** [comment]
I get this similar error with apk, yarn, etc that uses https certificates. Do you know or have procedures to put local Zscaler certificates into docker containers without Dockerfile copy each time?DanSent from my iPhoneOn Nov 24, 2022, at 11:06 PM, Michael Irwin ***@***.***> wrote:﻿
It looks like you're doing something that's not part of our tutorial, but we can try to help out. Looking at the error message you're getting, the version of Jest you're trying to use isn't compatible with the version of Node you're using. So, either update Node to a newer version or rollback Jest to an older version.
FWIW... we just merged in quite a few updates to have the app use the latest versions of Node, Jest, etc. The image is still building and being deployed, but you might want to give that a try and see if it helps at all.

**Comment by mikesir87** [comment]
Unfortunately, there isn't currently a known good way to get custom certs into every image beyond modifying the images to include your custom cert CA roots. Seeing that that's beyond the scope of the getting started guide, I'm going to close this issue. But, happy to continue the conversation either here or elsewhere. 

A quick Google search found [this article](https://www.bobbydurrettdba.com/2022/04/15/docker-sample-application-behind-zscaler/) that has a comment describing using the `HTTP_PROXY` and `HTTPS_PROXY` env vars, loading the CA cert, and getting it all to work  with yarn. I recognize it's a pain, but not much else we can do with that environment.
