### ISSUE TITLE
Possible typo in Persist Our Todo App

### ISSUE THREAD

**Issue by clfaulkner** [docker/getting-started#41]
The following line in #2 instruction of Persist Our Todo Data App raised errors until I modified it:
`docker run -dp 3000:3000 -v todo-db:/etc/todos getting-started`

Here is the modified line:
`docker run -dp 3000:3000 -v todo-db:/etc/todos <myuserid>/getting-started`

Of course, I used my actual id for `<myuserid>`  :-)

I also cleared out all my containers; don't know if that affected the outcome, or not.

**Comment by mikesir87** [comment]
Hi @clfaulkner and thanks for taking the time to submit an issue. We apologize that it's taken so long for us to get back to you.

At this point of the tutorial, either approach should work the same way as the images should be the same (the previous section retagged the `getting-started` image with `<myuserid>/getting-started`. At times, we purposely leave out the username, as it reduces the ability to simply copy/paste the command to run (you have to modify it first). Hence why it's using the `getting-started` image name. Hope that makes sense!

If you have other ideas/questions/comments, feel free to open a new issue and start a discussion. Thanks again!
