### ISSUE TITLE
ToDo app documentation needs clarification

### ISSUE THREAD

**Issue by AsiehH** [docker/getting-started#42]
The documentation located on the following link needs some clarifications

http://localhost/tutorial/our-application/
Under **"Building the App's Container Image"**, 
1-Should clarify where to create the Dockerfile. 
2-Should clarify from which folder to run the build command. 

I had downloaded and unzipped the _app_ folder under /docker on my computer. 
I had then created the Dockerfile inside the /docker folder and ran the build command from /docker path. It downloaded layers but when I ran `docker container ls -a`it showed nothing under port. So I couldn't open the app in the browser by going to  http://localhost:3000.

I stopped and removed the container and started from scratch, but this time
1-I created the Dockerfile inside the app folder
2-I  `cd` to app folder and then ran the build command. 
3-this time running `docker container ls -a` does show _0.0.0.0:3000->3000/tcp_ under ports and I was able to open the app in the browser by going to  http://localhost:3000.

**Comment by StefanScherer** [comment]
Thanks @AsiehH 
In the meantime we've updated the tutorial. It now should be more clear where to create the Dockerfile and where to run the build command.
Let me know if we still can improve that part.
