### ISSUE TITLE
Add .dockerignore file for node_modules

### ISSUE THREAD

**Issue by dmahnkopf** [docker/getting-started#46]
paragraph: `tutorial/image-building-best-practices/#layer-caching`

To make use of Layer Caching following Dockerfile for the todo app is proposed:

```dockerfile
FROM node:12-alpine
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --production
COPY . .
CMD ["node", "/app/src/index.js"]
```

This works as intended but could lead to possibly overwriting modules installed within the image if on the host a `node_modules` folder already exists and is outdated.

I guess a simple fix would be to add a 1-2 line `.dockerignore` file [like proposed by Node.js](https://nodejs.org/en/docs/guides/nodejs-docker-webapp/#dockerignore-file).

If You think adding a short introduction into `.dockerignore` files is not beyond the scope of this tutorial, I would be happy to assist with that.

**Comment by mikesir87** [comment]
Thanks for the issue @dmahnkopf! I think it’s a great idea to add both the file and a brief explanation. It doesn’t need to be anything complex, but could be “create this file” and a link or two to references. If you want to try writing something, we can certainly review it and get it merged in!
