### ISSUE TITLE
Typo in Using Docker Compose

### ISSUE THREAD

**Issue by jrobinson041** [docker/getting-started#5]
Typo in tutorial section using-docker-compose

simply -> simplify

**Comment by mikesir87** [comment]
Thanks for reporting the typo! Would you like to submit a PR for the fix?

**Comment by mikesir87** [comment]
Ah! Just barely overlapped with you! Taking a look at it now

**Comment by mikesir87** [comment]
Just letting you know that the updated image has been built and pushed. Thanks again!

**Comment by jrobinson041** [comment]
Thank you!
