### ISSUE TITLE
Updating our app should include rebuliding docker image

### ISSUE THREAD

**Issue by nmiquan** [docker/getting-started#52]

**Comment by azdaly** [comment]
I believe this is correct. I tried 
`docker run -dp 3000:3000 getting-started`  
and it didn't work update the app (that had the updated app.js file) until I first redid:
`docker build -t getting-started`  
I'd love to get confirmation though!

**Comment by StefanScherer** [comment]
The tutorial shows the command to build a new image right after modifying the html file.

![updating-docker-build](https://user-images.githubusercontent.com/207759/86112456-46118400-bac8-11ea-8504-b43c586ef049.jpg)
