### ISSUE TITLE
Windows not recognising {PWD} command

### ISSUE THREAD

**Issue by theendofsilence** [docker/getting-started#53]
I'm trying to follow the tutorial after installing Docker for Windows and I'm struggling on the How to use Bind Mounts section onwards.

The ${PWD} is not working and the multiple lines are not accepted as a single command. I've removed the "\" from each line and done it as a single line and made some progress.... but its throwing me.

Grateful for help understanding why I can't use the copy/paste option

**Comment by gardsvoll** [comment]
I have the exact same problem. I've tried several different manual path inputs instead of the PWD, but so far without luck.

**Comment by devra1** [comment]
I am guessing that you are both trying to run this in a Command Prompt (i.e. what was the old DOS Box)?
If you use the Windows Powershell, or as I am, in WSL 2 under Windows ver. 2004, then $PWD is correctly interpreted.

**Comment by theendofsilence** [comment]
> I am guessing that you are both trying to run this in a Command Prompt (i.e. what was the old DOS Box)?
> If you use the Windows Powershell, or as I am, in WSL 2 under Windows ver. 2004, then $PWD is correctly interpreted.

Yes, I was. Never used powershell before.

**Comment by toro-** [comment]
Hi there
I experienced some odd issues with this one too, raised an issue on here a while back.

Here's my finding raise on issue  https://github.com/docker/getting-started/issues/14

**Comment by StefanScherer** [comment]
I've opened #70 to show the PowerShell commands. I'm not sure what we should do about classic cmd.exe shells.
