### ISSUE TITLE
docker build giving error in "yarn install"

### ISSUE THREAD

**Issue by adilmujeeb** [docker/getting-started#56]
Checking the docker tutorial for building "getting-started" image, 

When I executed - 
$ docker build -t docker101tutorial .

It gives error:

-------------8<-------------------
yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/bytes/-/bytes-3.1.0.tgz: unable to get local issuer certificate".
info If you think this is a bug, please open a bug report with the information provided in "/app/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command '/bin/sh -c yarn install' returned a non-zero code: 1
-------------8<-------------------

When updated the dockerfile with below line before (RUN yarn install) solves the problem.
-------------8<-------------------
RUN yarn config set "strict-ssl" false -g
-------------8<-------------------

Dockerfile should be updated.

**Comment by StefanScherer** [comment]
Thanks for your report. That looks like either a network issue or an outdated local base image.
I ran the command right now and cannot see any problems with it.
Thanks for the suggestion, but we won't add this command as this would teach users how to turn off security and this is not intended.

Please update the cloned git repo and retry the build. What might help is 

```
git pull
docker build --pull --no-cache -t docker101tutorial .
```

This updates the local copy if the GitHub repo, pulls the fresh base images used and skips the local build cache, just to be sure that all latest bits are used.

**Comment by lesterpotter** [comment]
@StefanScherer - using your suggested commands, I still get the yarn error in the original post.  Note however that if I run the "docker build ..." line multiple times the error occurs with other URL paths.

"/content-type/-/content-type-1.0.4.tgz" for example
as well as the origin path "/bytes/-/bytes-3.1.0.tgz"

MacBook Pro Catalina
Docker 19.03.12

**Comment by StefanScherer** [comment]
@lesterpotter I've built it several times and cannot see these errors. Maybe you could try to use a different network (eg. no company network that may be restricted). Otherwise I have no idea why it fails.

**Comment by lesterpotter** [comment]
Yes, after disconnecting from my VPN, I was able to continue.

**Comment by ronwelsh** [comment]
I'm getting a yarn install error, as well - 

 > [app-base 5/9] RUN yarn install:
#15 0.344 yarn install v1.22.5
#15 0.412 [1/4] Resolving packages...
#15 0.712 [2/4] Fetching packages...
#15 0.959 error An unexpected error occurred: "https://registry.yarnpkg.com/body-parser/-/body-pa
rser-1.19.0.tgz: unable to get local issuer certificate".
#15 0.959 info If you think this is a bug, please open a bug report with the information provided
 in "/app/yarn-error.log".
#15 0.959 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command
.
------
executor failed running [/bin/sh -c yarn install]: exit code: 1
PS C:\Users\rwelsh\getting-started>

**Comment by KangShanR** [comment]
![image](https://user-images.githubusercontent.com/26142142/104921529-6a856d00-59d4-11eb-9c62-1efa8c3a4df6.png)
I'm getting a blocking on "Building fresh packages..."

**Comment by ian-mtb** [comment]
I'm getting the same thing, both on work laptop/VPN, work laptop w/o VPN, and home laptop.  This is extremely frustrating.

**Comment by sibelius** [comment]
anybody fixed this issue?

**Comment by StefanScherer** [comment]
I've built it yesterday and today again, and it works fine. 
We've updated the image on Docker Hub yesterday to add a fix for Apple Silicon.
I went through the Docker Desktop Getting Started Guide that you can find in the whale menu.
I wonder why it doesn't work for you 🤔 
So I'm checking again if adding `RUN yarn config set "strict-ssl" false -g` is a good idea.

**Comment by stephenpatten** [comment]
Hello,

Same issue.

Corporate VPN user with Zscaler running on the laptop. Spent the last day learning how to install the Zscaler.crt into the docker build file.

Here's the modified script that still has an error:

FROM node:12-alpine
RUN apk update && apk add --no-cache ca-certificates curl python g++ make && rm -rf /var/cache/apk/*
COPY ./zscalerrootca.crt /usr/local/share/ca-certificates/zscalerrootca.crt
RUN update-ca-certificates
WORKDIR /app
COPY . .
RUN export NODE_OPTIONS=--use-openssl-ca
RUN export NODE_EXTRA_CA_CERTS=/usr/local/share/ca-certificates/zscalerrootca.crt
RUN yarn install --production
CMD ["node", "src/index.js"]


------
 > [9/9] RUN yarn install --production:
#14 0.432 yarn install v1.22.5
#14 0.489 [1/4] Resolving packages...
#14 0.705 [2/4] Fetching packages...
#14 1.127 error An unexpected error occurred: "https://registry.yarnpkg.com/bytes/-/bytes-3.1.0.tgz: unable to get local issuer certificate".
#14 1.128 info If you think this is a bug, please open a bug report with the information provided in "/app/yarn-error.log".
#14 1.128 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
------
executor failed running [/bin/sh -c yarn install --production]: exit code: 1

and it the same error with the unaltered script.

Any pointers as to corrected the script?

Thank you,
Stephen

**Comment by gajjalaanvesh** [comment]
@stephenpatten 

This is the exact error I encountered.
I have Zscaler installed too on my office laptop. 

**#14 1.292 error An unexpected error occurred: "https://registry.yarnpkg.com/depd/-/depd-1.1.2.tgz: unable to get local issuer certificate".**

**Docker File content from the Tutorial:** 
FROM node:12-alpine
RUN apk add --no-cache python g++ make
WORKDIR /app
COPY . .
RUN yarn install --production
CMD ["node", "src/index.js"]

**You just have to modify the RUN line to this**
RUN "**yarn config set strict-ssl false -g** && yarn install --production"

NOTE: you may encounter this error throughout the getting-started tutorial.

Please refer below link, it may help you.
https://github.com/docker/getting-started/issues/157#issue-898736220

**Comment by stephenpatten** [comment]
@StefanScherer 

Tried the very basic steps you mentioned in the beginning of the thread.

docker build --pull --no-cache -t docker101tutorial .
[+] Building 30.4s (18/29)
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 1.08kB                                                                             0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 52B                                                                                   0.0s
 => [internal] load metadata for docker.io/library/nginx:alpine                                                   15.9s
 => [internal] load metadata for docker.io/library/python:alpine                                                  11.0s
 => [internal] load metadata for docker.io/library/node:12-alpine                                                  9.3s
 => [auth] library/python:pull token for registry-1.docker.io                                                      0.0s
 => [auth] library/nginx:pull token for registry-1.docker.io                                                       0.0s
 => [auth] library/node:pull token for registry-1.docker.io                                                        0.0s
 => [stage-5 1/3] FROM docker.io/library/nginx:alpine@sha256:91528597e842ab1b3b25567191fa7d4e211cb3cc332071fa031  14.4s
 => => resolve docker.io/library/nginx:alpine@sha256:91528597e842ab1b3b25567191fa7d4e211cb3cc332071fa031cfed2b58  14.4s
 => [internal] load build context                                                                                  0.2s
 => => transferring context: 10.37MB                                                                               0.1s
 => CACHED [app-base 1/8] FROM docker.io/library/node:12-alpine@sha256:05328aa871f251b0643b8dcaa01034f126a8343b51  0.0s
 => [base 1/4] FROM docker.io/library/python:alpine@sha256:3998e97aeeabfdeea57c6e05c7544c460ae158f24cc74371b7d4e  14.4s
 => => resolve docker.io/library/python:alpine@sha256:3998e97aeeabfdeea57c6e05c7544c460ae158f24cc74371b7d4eca18f  14.4s
 => [app-base 2/8] RUN apk add --no-cache python g++ make                                                         12.6s
 => [auth] library/nginx:pull token for registry-1.docker.io                                                       0.0s
 => [auth] library/python:pull token for registry-1.docker.io                                                      0.0s
 => [app-base 3/8] WORKDIR /app                                                                                    0.1s
 => [app-base 4/8] COPY app/package.json app/yarn.lock ./                                                          0.1s
 => ERROR [app-base 5/8] RUN yarn install                                                                          1.6s
------
 > [app-base 5/8] RUN yarn install:
#15 0.629 yarn install v1.22.5
#15 0.717 [1/4] Resolving packages...
#15 1.100 [2/4] Fetching packages...
#15 1.548 error An unexpected error occurred: "https://registry.yarnpkg.com/content-type/-/content-type-1.0.4.tgz: unable to get local issuer certificate".
#15 1.548 info If you think this is a bug, please open a bug report with the information provided in "/app/yarn-error.log".
#15 1.548 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
------
executor failed running [/bin/sh -c yarn install]: exit code: 1

I have also created chimmined in with the node/yarn folks.

-Stephen

**Comment by ebresie** [comment]
Trying the getting started tutorial and have tweaked it some (behind corp firewall) but still have problems.  My current

```
FROM node:12-alpine
RUN apk update && apk add --no-cache tar nodejs yarn python g++ make ca-certificates && rm -rf /var/cache/apk/*
WORKDIR /app
COPY . .
## Setup ca certificates for environment - believe may with the local cert issuer
COPY Certs/myCert.crt /usr/local/share/ca-certificates/myCert.crt
RUN chmod 644  /usr/local/share/ca-certificates/myCert.crt && update-ca-certificates
# tell node where to look for ca certs
RUN export NODE_OPTIONS=--use-openssl-ca
RUN export NODE_EXTRA_CA_CERTS=/usr/local/share/ca-certificates/myCert.crt
# clear out yarn cache - tried with and without
RUN yarn cache clean
# gets yarn to not confirm to strict SSL checks
RUN yarn config set "strict-ssl" false
# RUN yarn set version 1.22.5
# This ticket said it was fixed with 1.16.0 1.22.5, and latests) and none of these worked
# set the specific yarn version to use
RUN yarn set version 1.16.0
# setup yarn to load applicable dependencies with verbose and extra network timeout allocated
RUN yarn install --production --verbose --network-timeout 2000000
CMD ["node", "src/index.js"]
```

After running this it seems to get pretty far based on the verbose details but seems to fail following getting the "prettier" dependency (see line below) and in my case after about what indicates as 305 (seconds I believe) 

```
#17 305.9 verbose 305.444603 Performing "GET" request to "https://registry.yarnpkg.com/yallist/-/yallist-2.1.2.tgz".
#17 306.1 verbose 305.6707276 Performing "GET" request to "https://registry.yarnpkg.com/prettier/-/prettier-1.18.2.tgz".
```

Does this give anyone else any ideas?

**Comment by ataffe** [comment]
I had this same issue (behind a corp firewall). I got it to work by adding my company's zscalar cert to the app directory. So my app directory looks like this:

```
Dockerfile
company_cert.pem 
node_modules
package.json
spec
src
```

Then I added docker commands to 
1. Add the company cert to /etc/ssl/certs/ in the container
2. Set the yarn cafile path to /etc/ssl/certs/company_cert.pem

So my docker file looks like this now:

```
FROM node:12-alpine
RUN apk add --no-cache python g++ make
WORKDIR /app
COPY . .
ADD company_cert.pem /etc/ssl/certs/company_cert.pem
RUN yarn config set cafile /etc/ssl/certs/PayPalRoot.pem
RUN yarn install
CMD ["node", "src/index.js"]
```

**Comment by Amack34** [comment]
finally got it working after adding RUN "yarn config set strict-ssl false -g && yarn install --production", and ARG PROXY="corporate proxy address"
RUN sed -i 's/https/http/' /etc/apk/repositories
RUN export HTTP_PROXY=$PROXY && export HTTPS_PROXY=$PROXY && \
apk update

**Comment by joey1089** [comment]
issue with "yarn install --production" is clearly a network issue, I wasn't able to run in my laptop but I was able do it in ACG cloud server.

**Comment by cloudGrin** [comment]
I also encountered the same problem, the reason is that I used a third-party image, just switch to the default builder,

`docker buildx create --use --name=mybuilder --driver docker-container`

**Comment by cloudGrin** [comment]
> 

https://hub.docker.com/r/dockerpracticesig/buildkit

**Comment by mikesir87** [comment]
Sorry about that... meant to write a comment before closing! The errors occur when either network issues occur or when using corporate proxies. Unfortunately, both of those are either beyond our control or beyond the scope of the getting started guide.

**Comment by OfirYC** [comment]
Potential quick fix: Look for any unwanted leftover lines in your docker file. In my case there was a random line i forgot to remove

**Comment by doctorx32** [comment]
in new Docker versions such as >23, docker build output does not reason of error, for me it was incompatible version of node in package.json. Figured this out at the other machine with docker 20.10.6 output

**Comment by llzzzzoo** [comment]
I solved the problem in tow steps. The first step is to transform the network connection from wifi to a mobile network, and the second step is to close VPN.

**Comment by natan-matos** [comment]
In my case, I solved the problem using a VPN.

**Comment by juanAntonio121** [comment]
Despues de intentar varias soluciones he encontrado la solucion al problema en mi caso y posiblemente el de algunos.. 

**Este es mi Dockerfile:**

# Este es un Dockerfile de múltiples etapas y requiere Docker >= 17.05
# https://docs.docker.com/engine/userguide/eng-image/multistage-build/
FROM golang:alpine as builder

ENV GOPROXY http://proxy.golang.org

RUN mkdir -p /src/handshake
WORKDIR /src/handshake

# Instalar certificados para acceso a la red
RUN apk add --no-cache ca-certificates

# Inicializar el módulo Go
RUN go mod init handshake

# Instalar Buffalo
RUN apk add --no-cache git wget
RUN wget https://github.com/gobuffalo/cli/releases/download/v0.18.14/buffalo_0.18.14_Linux_x86_64.tar.gz && \
    tar -xvzf buffalo_0.18.14_Linux_x86_64.tar.gz && \
    mv buffalo /usr/local/bin/buffalo

# Esto cacheará el paso de instalación de npm, a menos que cambie el package.json
ADD package.json .
ADD yarn.lock .yarnrc.yml ./
RUN mkdir .yarn
COPY .yarn .yarn
RUN apk add --no-cache nodejs npm yarn && yarn install

# Copiar los manifiestos de módulos Go
COPY go.mod go.mod
COPY go.sum go.sum

# Cachear las dependencias antes de construir y copiar el código fuente para que no sea necesario volver a descargar tanto y para que los cambios en el código fuente no invaliden nuestra capa descargada
RUN go mod download

# Copiar el código fuente de la aplicación
ADD . .

# Construir la aplicación usando Buffalo
RUN buffalo build -o /bin/app

# Etapa final
FROM alpine

# Instalar bash y certificados
RUN apk add --no-cache bash ca-certificates

# Establecer directorio de trabajo
WORKDIR /bin/

# Copiar el binario construido desde la etapa de construcción
COPY --from=builder /bin/app .

# Descomentar para ejecutar el binario en modo "producción":
# ENV GO_ENV=production

# Vincular la aplicación a 0.0.0.0 para que pueda ser vista desde fuera del contenedor
ENV ADDR=0.0.0.0

# Exponer el puerto 3000
EXPOSE 3000

# Descomentar para ejecutar las migraciones antes de ejecutar el binario:
# CMD /bin/app migrate; /bin/app

# Comando para ejecutar la aplicación
CMD exec /bin/app




**y este es mi docker-compose.yml:**

version: '3.9'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydatabase

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "mydefaultemail"
      PGADMIN_DEFAULT_PASSWORD: "mypassword"

  buffalo:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgres://root:root@postgres:5432/mydatabase"  # Cambiar esto si es necesario
