### ISSUE TITLE
mysql 5.7 issue and 8+ auth

### ISSUE THREAD

**Issue by TrevorTaylor-TP** [docker/getting-started#59]
When trying to setup the mysql database and container with version 5.7 it fails to start. When using 8 or higher, there is an authentication issue since 8 doesnt use the old password method. Is there a way to set up the sql server with a mysql 8 using their new authentication methods?

**Comment by mikesir87** [comment]
Thanks for submitting an issue @TrevorTaylor-TP and apologies for the delay in getting back to you. Fortunately, we've made updates to the tutorial that have bumped up the versions of both MySQL and the libraries we're using... which resolves this issue. 

If you find other issues, feel free to create a new issue!
