### ISSUE TITLE
Getting starting command mismatch 

### ISSUE THREAD

**Issue by pivendren** [docker/getting-started#61]
I did a clean install of Docker Desktop for Windows and I noticed the get started command in the dashboard is the one below:
```docker run -dp 80:80 docker/getting-started```

Running the command and then navigating to the Getting Started page of the running container breaks down this command:
```docker run -d -p 80:80 docker/getting-started```

It is a relatively small variance using ```-dp``` vs ```-d -p``` but could be confusing to newcomers. Any ideas on how we could make this a little better? I am happy to create a PR for it.

**Comment by StefanScherer** [comment]
Thanks @pivendren for explaining. I agree this might be a bit confusing for beginners.
But the tutorial has the "Pro tip" box below and shows the `-dp` flag and explains that it can be combined. Is the box too late? Should we swap the commands? Should we change the command in the empty dashboard of Docker Desktop?

I you have a good suggestion I'm happy to review a PR :-)

**Comment by pivendren** [comment]
Ideally, the change would happen in Docker Desktop to make the progression to the pro tip cleaner. I really like the pro tip because it highlights that there are alternates/short commands.

I could not find a repo for Docker desktop so not sure how I can help on that front.

**Comment by StefanScherer** [comment]
We've updated the command in the dashboard to use `-d -p 80:80`. You will see this in the next updates. Thanks for bringing up this detail.
