### ISSUE TITLE
Failed to Run the Example in `Persisting our DB`

### ISSUE THREAD

**Issue by hc128168** [docker/getting-started#93]
I followed the [tutorial](https://www.docker.com/101-tutorial) to install and run `docker/getting-started` container.

And I ran into an issue:
```
$ sudo docker run -d ubuntu -c "shuf -i 1-10000 -n 1 -o /data.txt && tail -f /dev/null"
Unable to find image 'ubuntu:latest' locally
latest: Pulling from library/ubuntu
d72e567cc804: Pull complete 
0f3630e5ff08: Pull complete 
b6a83d81d1f4: Pull complete 
Digest: sha256:bc2f7250f69267c9c6b66d7b6a81a54d3878bb85f1ebb5f951c896d13e6ba537
Status: Downloaded newer image for ubuntu:latest
84ea529f74a5824fd3a5d21a6deb01f97d291eb26c95a21883ddccb85ee2b129
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"-c\": executable file not found in $PATH": unknown.

```
I was following this chapter http://localhost/tutorial/persisting-our-data

Seems like `exec` is missing the `ubuntu`'s image?

**Comment by sujirou** [comment]
on your `docker run` command, you forgot to include "`bash`" right before the "`-c `" switch. should be right after "`ubuntu`".

try it again:
`docker run -d ubuntu bash -c "shuf -i 1-10000 -n 1 -o /data.txt && tail -f /dev/null"`

**Comment by mikesir87** [comment]
Closing this issue as it appears the issue has been answered (thanks @sujirou!).

If you have future questions or issues, feel free to create a new issue and we'll be happy to help out (and will respond much more quickly too!). Thanks all!
